### ISSUE TITLE
Error: Cannot find module 'vs/editor/contrib/gotoSymbol/goToCommands'

### ISSUE THREAD

**Issue by Lionelpang** [egoist/svg2vue#1]
hello, build the project through npm build, Abnormal Report。 the error message flow:
> svg2vue@1.0.0 build /Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue
> poi --prod

Error: Cannot find module 'vs/editor/contrib/gotoSymbol/goToCommands'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.resolve (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at resolveMonacoPath (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/monaco-editor-webpack-plugin/out/index.js:34:28)
    at use.options.pre.featurePaths.map (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/monaco-editor-webpack-plugin/out/index.js:173:63)
    at Array.map (<anonymous>)
    at createLoaderRules (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/monaco-editor-webpack-plugin/out/index.js:173:43)
    at MonacoEditorWebpackPlugin.apply (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/monaco-editor-webpack-plugin/out/index.js:91:23)
    at webpack (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/webpack/lib/webpack.js:51:13)
    at PoiCore.createWebpackCompiler (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/poi/lib/index.js:469:40)
    at CAC.command.cli.command.usage.action (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/poi/lib/index.js:147:31)
    at CAC.runMatchedCommand (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/cac/dist/index.js:611:34)
    at PoiCore.run (/Users/lionel/CusData/Projects/Other/tmp/vue-svg/svg2vue/node_modules/poi/lib/index.js:337:20)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svg2vue@1.0.0 build: `poi --prod`

**Comment by Lionelpang** [comment]
how to resolve? thanks!
